<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: user.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'Student Score Management'=>'学生成绩管理',
	'welcome to student score management system'=>'欢迎进入学生成绩管理系统',
	'Show Scores and Query'=>'学生分数查询',
	'Show analysis'=>'学生分数分析',
	'Manage'=>'管理',
	'Query'=>'查询',
	'welcome to student score management query'=>'欢迎进入学生成绩查询功能',
	'Show Analysis'=>'学生分数分析',
	'Advanced Search'=>'高级搜索',
	'Student Achievements analysis'=>'学生分数分析',
	'welcome to student score management analysis'=>'欢迎进入学生成绩分析功能',
);