<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
		'QuestionBank Management'=>'题库管理',
		'Paper Management'=>'试卷管理',
		'Create Paper'=>'添加试卷',
		'PaperBank Management'=>'试卷库管理',
		'Students Online Test'=>'学生在线自测',
		'Statistics Analysis'=>'成绩统计分析',
		
		'Statistics Analysis of Questions'=>'题目统计分析',
		'Statistics Analysis of Paper'=>'显示试卷分析',
		'Historical Performance'=>'历史成绩统计',
);
