<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Create Assignment' => '布置作业',
  'Assignments' => '作业',
  'Name' => '作业题目',
  'Upload homework' => '上交作业',
  'Create Assignment' => '布置作业',
  'Manage Assignment' => '管理已布置的作业',
  'Dead Line' => '截止日期',
  'Manage' => '管理',
  'List Assignment' => '列出已经布置的作业',
  'Update' => '更新',
  'View Assignment' => '查看布置的作业',
  'Requirement' => '作业要求',
  'Download' => '作业下载',
  'Click here' => '点击这里',
  'Update Assignment' => '更新作业要求',
  'Delete Assignment' => '取消作业',
  'Teachingclass' => '教学班',
  'Resource' => '附件',
  'Is Published' => '是否发布',
  'Teacher' => '任课教师',
);
