<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Create Homework' => '上传作业',
  'Homeworks' => '提交作业系统',
  'Manage Homework' => '管理提交的作业',
  'Description' => '作业描述',
  'Download' => '下载作业', 
  'Click Here' => '点击这里',
  'Manage' => '管理',
  'List Homework' => '列出作业',
  'Create' => '提交',
  'View Homework' => '查看上交的作业',
  'Update Homework' => '改作业',
  'Delete Homework' => '删除作业',
  'Student' => '学生编号',
  'Score' => '得分',
  'Assignment' => '对应作业',
  'Resource' => '作业附件',
  'Comments' => '教师评语',
  'Teachingclass' => '教学班',
  'Submit Time' => '提交时间',
  'Name' => '学生姓名',
);
