<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  	'Create ResResource' => '上传资源',
  	'Res Resources' => '资源系统',
  	'Manage ResResource' => '管理资源',
	'Search ResResource' => '搜索资源',
	'Manage Comments' => '管理评论',
	'List ResResource' => '我的资源',
	'Download ResResource' => '下载资源',
	'Manage' => '管理',
	'Create' => '上传',
	'Search' => '搜索',
	'Update' => '更新',
	'View ResResource' => '查看资源',
	'ResResource'=>'资源',
	'Resource ID'=>'资源编号',
	'Path'=>'路径',
	'Resource Name'=>'资源名称',
	'Uploader'=>'上传者',
	'Download Count'=>'下载数',
	'Resource Type' => '资源类型',
	'Resource Description' => '资源描述',
	'Upload Time' => '上传时间',
	'Update ResResource'=>'更新资源',
	'Delete ResResource'=>'删除资源'
);
