<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: base.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'Class Basic Infos'=>'班级信息',
	'Manage Class Basic Infos'=>'管理班级信息',
	'Manage ClassBasicInfo'=>'管理班级信息',
	'List ClassBasicInfo'=>'班级信息列表',
	'Create ClassBasicInfo'=>'创建班级',
	'Class Name'=>'班级名称',
	'Grade'=>'年级',
	'Tutor'=>'班主任',
	'Batch Create Class'=>'批量创建班级',
	'Batch Create'=>'批量创建',
	'ClassBasicInfo Data File'=>'班级基本信息文件',
	'{attribute} Invalid file format.'=>'{attribute} 无效的文件格式.',
		'Input format: csv, UTF-8 encoded, with format "name, grade, tutor_id" per line, leading & trailing whitespace ignored.'=>'输入格式: csv 文件, UTF-8 编码, 每行格式 "班级名, 年级, 班主任 ID", 首尾空白忽略.',
);