<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: user.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'Course Code'=>'课程代码',
	'Course Name'=>'课程名称',
	'Course Credit'=>'学分',
	'Course Class'=>'类别',
	'Course List'=>'课程列表',
	'Course'=>'课程',
	'Prerequsite Required'=>'预修要求',
	'Introduction'=>'简介',
	'Syllabus'=>'教学大纲',
	'Department'=>'所属院系',
	'Priority'=>'优先级',
);
