<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: user.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'Name'=>'课程名称',
	'Credit'=>'学分',
	'Class'=>'类别',
	'Course'=>'课程',
	'Prerequsite Required'=>'预修要求',
	'Introduction'=>'简介',
	'Statement'=>'申请理由',
	'Syllabus'=>'教学大纲',
	'Department'=>'所属院系',
	'Priority'=>'优先级',
	'Create CourseWaitlist'=>'申请新课',
	'Course Waitlists'=>'课程申请列表',
	'Create'=>'创建新课程',
	'View'=>'查看新课程',
	'List CourseWaitlist'=>'列出课程申请',
	'Manage CourseWaitlist'=>'管理课程申请',
	'Manage'=>'管理',
	'Manage Course Waitlists'=>'管理课程申请',
	'View CourseWaitlist'=>'查看课程申请',
	'Update CourseWaitlist'=>'更新课程',
	'Delete CourseWaitlist'=>'删除课程',
	'Course Confirm'=>'课程审核',
	'Status'=>'审核状态',
);
