<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: department.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'List Department'=>'学院列表',
	'Create Department'=>'创建学院',
	'Manage Department'=>'管理学院',
	'Batch Create Department'=>'批量创建学院',
	'Delete Department'=>'删除学院',
	'Batch Create'=>'批量创建',
	'Input format: csv, UTF-8 encoded, with one name of department per line, leading & trailing whitespace ignored.'=>'输入格式: csv 文件, UTF-8 编码, 每行一个学院的名字, 首尾空白忽略.',
	'Name'=>'名称',
	'ID'=>'ID',
	'Department Data File'=>'学院数据文件',
	'{attribute} Invalid file format.'=>'{attribute} 无效的文件格式.',
	'Departments'=>'学院管理',
);
