<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: user.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'Advanced Search'=>'高级搜索',
	'Fields with <span class="required">*</span> are required.'=>'带有 <span class="required">*</span>的项目必须填写.',
	'Submit'=>'提交',
	'Input format: csv, UTF-8 encoded, with format "student_id, current_grade, program_id, entry_date, class_id, remark, first_name, last_name, sex, photo, date_of_birth, ethnic_group, political_status, birth_place_city, birth_place_province, original_residence_city, original_residence_province, home_address, home_postcode, home_phone, email, phone, identity_card_number" per line (introduction can have multiple lines, by enclosing it in double quotes), leading & trailing whitespace ignored.'=>'输入格式：使用csv文件,UTF-8编码,每行具有如下信息"学号,所在年级,院系,入学时间,班级,备注,姓,名,性别,照片,生日,民族,政治面貌,城市,省份,户口所在城市,户口所在省份,家庭住址,邮编,家庭电话,邮箱,电话,身份证号",多行使用双括号括起,首端和末端的空格将被忽略.',
	'Create'=>'创建',
	'Save'=>'保存',
	'Input format: csv, UTF-8 encoded, with format "name, grade, tutor_id" per line, leading & trailing whitespace ignored.'=>'输入格式：使用csv文件,UTF-8编码,每行具有如下信息"姓名,年级,班主任",多行使用双括号括起,首端和末端的空格将被忽略.',
	'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.'=>'你可以在最前端输入一个比较符 (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>或者 <b>=</b>) 来指明要进行的操作.',
	'Input format: csv, UTF-8 encoded, with format "name, department_id, length, year, introduction" per line (introduction can have multiple lines, by enclosing it in double quotes), leading & trailing whitespace ignored.'=>'输入格式：使用csv文件,UTF-8编码,每行具有如下信息"姓名,院系,学制,入学年份,简介",多行使用双括号括起,首端和末端的空格将被忽略.',
	'Input format: csv, UTF-8 encoded, with one name of department per line, leading & trailing whitespace ignored.'=>'输入格式：使用csv文件,UTF-8编码,每行一个学院名称,首端和末端的空格将被忽略.',

);
