<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: user.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'ID'=>'ID',
	'First Name'=>'名',
	'Last Name'=>'姓',
	'Sex'=>'性别',
	'Photo'=>'照片',
	'Date Of Birth'=>'出生日期',
	'Ethnic Group'=>'民族',
	'Political Status'=>'政治面貌',
	'Birth Place City'=>'出生城市',
	'Birth Place Province'=>'出生省份',
	'Original Residence City'=>'籍贯城市',
	'Original Residence Province'=>'籍贯省份',
	'Home Address'=>'家庭住址',
	'Home Postcode'=>'家庭邮编',
	'Home Phone'=>'家庭电话',
	'Email'=>'电子邮件',
	'Phone'=>'电话',
	'Identity Card Number'=>'身份证号码',
	'Invalid province/city combination.'=>'非法的省份/城市组合.',
	'Male'=>'男',
	'Female'=>'女',
	'Personal Info Data File'=>'个人信息数据文件',
	'{attribute} Invalid file format.'=>'{attribute} 无效的文件格式.',
	'Edit Personal Info'=>'编辑个人信息',
	'Create Personal Info'=>'创建个人信息',
	'Manage Personal Info'=>'管理个人信息',
	'Batch Create Personal Info'=>'批量生成个人信息',
	'Personal Infos'=>'个人信息',
	'List Personal Info'=>'个人信息列表',
	'Advanced Search'=>'高级搜索',
	'Image'=>'照片',
	'Update Personal Info'=>'更新个人信息',
	'Delete Personal Info'=>'删除个人信息',
	'View Personal Info'=>'查看个人信息',
);
