<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: base.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'ID' => '课程代码',
	'Program Details' => '培养方案中的课程',
	'Create ProgramDetail' => '向培养方案添加课程',
	'Manage ProgramDetail' => '管理培养方案中的课程',
	'List ProgramDetail' => '列出培养方案中的课程',
	'Manage Program Details' => '管理培养方案中的课程',
	'Create' => '创建',
	'Program' => '所属培养方案',
	'Course' => '课程 ID',
	'Type' => '课程类型',
	'Required' => '前置课程',
	'Recommended Year' => '推荐修读学年',
	'Recommended Term' => '推荐修读学期',
);