<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: user.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'Program'=>'培养方案',
	'Program Data File'=>'培养方案数据文件',
	'Name'=>'名称',
	'Type'=>'类型',
	'Capacity'=>'容量',
	'ID'=>'ID',
	'Department'=>'院系',
	'Grade'=>'年级',
	'Length'=>'学制',
	'Introduction'=>'介绍',
	'Invalid department ID.'=>'无效的学院 ID.',
	'List Program'=>'培养方案列表',
	'Create Program'=>'创建培养方案',
	'Manage Program'=>'管理培养方案',
	'Batch Create Program'=>'批量创建培养方案',
	'Delete Program'=>'删除培养方案',
	'Batch Create'=>'批量创建',
	'{attribute} Invalid file format.'=>'{attribute} 无效的文件格式.',
	'Input format: csv, UTF-8 encoded, with format "name, department_id, length, year, introduction" per line (introduction can have multiple lines, by enclosing it in double quotes), leading & trailing whitespace ignored.'=>'输入格式: csv 文件, UTF-8 编码, 每行格式 "名字, 学院 ID, 学制, 年级, 简介" (可将简介用双引号括起, 以允许多行), 首尾空白忽略.',
);
