<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: user.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'ID'=>'ID',
	'SystemAdminID'=>'管理员编号',
	'Current Grade'=>'所在年级',
	'Program'=>'专业',
	'Entry Date'=>'入学时间',
	'Class'=>'班级',
	'Remark'=>'备注',
	'Personal Info ID'=>'个人信息号',
	'SystemAdmin Basic Info'=>'系统管理员基本信息',
	'Create Basic Info'=>'创建系统管理员基本信息',
	'Manage Basic Info'=>'管理系统管理员基本信息',
	'System Admin Basic Info'=>'管理系统管理员基本信息',
	'Batch Create Info'=>'批量创建系统管理员基本信息',
	'List Basic Info'=>'系统管理员基本信息列表',
	'SystemAdmin Basic Info File'=>'系统管理员基本信息文件',
	
);
