<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 * 作为4类用户公共的文件
 * @version $Id: user.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
  'ID'=>'ID',
  'Login'=>'登录',
  'Logout'=>'登出',
  'Password'=>'密码',
  'password'=>'密码',
  'New Password'=>'新密码',
  'New Password Repeat'=>'重复新密码',
  'Change Password'=>'修改密码',
  'Student'=>'学生',
  'Teacher'=>'教师',
  'Administrator'=>'管理员',
  'System administrator'=>'系统管理员',
  'Information Management'=>'信息管理',
  'User type'=>'用户类型',
  'Type'=>'类型',
  'Remember me next time'=>'下次记住我',
  'Username'=>'用户名',
  'Incorrect username or password.'=>'错误的用户名或密码.',
  'Incorrect password.'=>'错误的密码.',
  'No'=>'否',
  'Yes'=>'是',
  'Student Basic Info Data File'=>'学生基本信息数据文件',
  'Teacher Basic Info Data File'=>'教师基本信息数据文件',
  'Batch Create'=>'批量创建',
  'List Student Basic Information'=>'查看学生基本信息',
  'Manage Student Basic Information'=>'管理学生基本信息',
  'Batch Create Student Basic Information'=>'批量创建学生基本信息',
  'Create Student Basic Information'=>'创建学生基本信息',
  'Input format: csv, UTF-8 encoded, with format "student_id, current_grade, program_id, entry_date, class_id, remark, first_name, last_name, sex, photo, date_of_birth, ethnic_group, political_status, birth_place_city, birth_place_province, original_residence_city, original_residence_province, home_address, home_postcode, home_phone, email, phone, identity_card_number" per line (introduction can have multiple lines, by enclosing it in double quotes), leading & trailing whitespace ignored.'=>
  '输入格式: csv 文件, UTF-8 编码, 每行格式 "学生 ID, 年级, 培养方案 ID, 入学日期, 班级 ID, 备注, 名, 姓, 性别, 照片, 出生日期, 民族, 政治面貌, 出生城市, 出生省份, 籍贯城市, 籍贯省份, 家庭住址, 家庭邮编, 家庭电话, 电子邮件, 电话, 身份证号码, " (可将简介用双引号括起, 以允许多行), 首尾空白忽略.',
  '{attribute} Invalid file format.'=>'{attribute} 无效的文件格式.',
  'Please fill out the following form with your login credentials:'=>'请使用你的登录验证信息填写下列表格:',
);
