<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: base.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	//////////////////////////////////主导航条
	'About'=>'关于',
	'Login'=>'登录',
	'Logout'=>'登出',
	'Error'=>'错误',
	'Course List'=>'课程列表',
	'Study Plan'=>'学习计划',
	'Personal Information'=>'个人信息',
	'Authorization Management'=>'权限管理',
	'Classrooms'=>'教室管理',
	'Class Manage'=>'班级管理',
	'Departments'=>'学院管理',
	'Programs'=>'培养方案',
	'Student Basic Information'=>'学生基本信息',
	'Teacher Basic Information'=>'教师基本信息',
	'Administrator Basic Information'=>'管理员基本信息',
	'System Administrator Basic Information'=>'系统管理员基本信息',
	'Course Arrangement Subsystem'=>'排课子系统',
	'Apply Class'=>'课程申请',
	'Classroom Management'=>'教室管理',
	'Course Selection'=>'选课',
	'Score Management'=>'成绩管理',
	'Course Waitlist'=>'课程申请',
	//////////////////////////////////业务名词
	'Teaching Service System'=>'教务管理系统',
	'Information Management'=>'信息管理子系统',
	'Test Online Subsystem'=>'在线测试子系统',
    'Resource Sharing Subsystem'=>'资源共享子系统',
	//////////////////////////////////按钮图标
	'Advanced Search'=>'高级搜索',
	'Operations'=>'操作',
	'Submit'=>'提交',
	'Create'=>'创建',
	'Save'=>'保存',
	'Change Password' => '修改密码',
	//////////////////////////////////提示交互
	'Fields with <span class="required">*</span> are required.'=>'标有 <span class="required">*</span> 的项目必填.',
	'Are you sure you want to delete this item?'=>'确定删除此条目?',
	'Course Name'=>'课程名称',
);
