<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: user.php 2879 2011-01-16 23:13:00Z qiang.xue $
 */
return array (
	'Course Arrangement'=>'排课',
	'courseArrangement'=>'排课',
	'New application'=>'教师课程申请',
	'Quary application'=>'查询申请',
	'Confirm application'=>'课程审核',
	'Class'=>'教学班',
	'Classroom'=>'教室',
	'Time'=>'上课时间',
	'Is Single'=>'单双周',
	'teacherid'=>'教师ID',
	
	'yuquan'=>'玉泉',
	'zijingang'=>'紫金港',
	'xixi'=>'西溪',
	'Course id does not exist!'=>'课程号不存在！',
	'room number exists!'=>'教室号已经存在！',
	'capacity is not valid!'=>'教室容量不合理！',
	'one classroom cannot have more than one class at a same time'=>'同一时刻同一教室不能有一个以上的课',
	'this class not exists'=>'这门课不存在啊',
	'this classroom not exists'=>'这教室不存在啊',
	'the teacher cannot have more than one class at same time'=>'一个老师不能在同一时间上两门课',
	'List ClassTime'=>'查询排课结果',
	'Create ClassTime'=>'新安排一门课',
	'Manage ClassTime'=>'管理排课结果',
	
	'Create Classroom'=>'新增教室',
	'Manage Classroom'=>'教室管理',
	'View Classroom'=>'教室查询',
);
